extern void 		DiskSetTofU(unsigned long);
extern void 		DiskSetMask (unsigned char *);
extern void 		DiskSetUptime(unsigned long);
extern void 		DiskSetIP (unsigned char *);
extern void 		DiskSetGate (unsigned char *);
extern void 		DiskSetDeltaUptime (unsigned long);
extern void 		DiskSetEpoch (long);
extern void 		DiskSetMac (unsigned int *);
extern void 		DiskSetTZ (long);
extern void 		DiskSetTZText (unsigned char *);
extern void 		DiskSetDns (unsigned char *);
extern void 		DiskGetDns (unsigned char *);
extern void 		DiskGetGate (unsigned char *);
extern unsigned long 	DiskGetDeltaUptime ();
extern long 		DiskGetTZ ();
extern void 		DiskGetTZText (unsigned char *);
extern long 		DiskGetEpoch ();
extern void 		DiskGetIP (unsigned char *);
extern void 		DiskGetMask (unsigned char *);
extern void 		DiskGetMac (unsigned int *);
extern unsigned long 	DiskGetTofU();
extern unsigned long 	DiskGetUptime(int);
extern void 		DiskRead (struct storage *);
extern void 		DiskWrite (struct storage *);
extern void 		DiskDumper ();
